algoritmo "Aula18. Ex5"
// Diciplina: Lógica de programação
// Autor : EduFM
// Data : 13/04/2026
var
// variaveis :3
   nome, senha: caracter

inicio

//Codiguinhos ^w^
          escreva ("Qual o nome do usuario: ")
          leia (nome)
          
          escreval ("Qual é a senha: ")
          leia (senha)
// uso do se
   se senha = "acb23" entao
      escreval ("senha correta")
   senao
        escreval ("senha incorreta")
   fimse

fimalgoritmo
