algoritmo "Aula18. Ex7"
// Diciplina: Lógica de programação
// Autor : EduFM
// Data : 14/04/2026
var
// variavel :3
   idade: Real

inicio
// Codiguinhos ^w^
   escreval ("Seu voto é obrigatório?")
   
   escreval ("Qual é a sua idade?")
   leia (idade)
   
//Agora é o uso do "if" °o°
   se idade >= 18 entao
      se idade >= 70 entao
         escreval ("O voto é opcional")
      senao
           escreval ("O voto é obrigatório")
      fimse
   senao
        se idade >= 16 entao
           escreval ("O voto é opicional")
        senao
             escreval ("Não tem idade para votar")
        fimse
   fimse

fimalgoritmo


