algoritmo "Aula18. Ex4"
// Diciplina: Lógica de programação
// Autor : EduFM
// Data : 13/04/2026
var
// Variaveis :3
   idade, valor1, valor2, valor3: Real

inicio

//Codiguinhos ^w^
          escreval ("Você tem idade para dirigir?")

          escreval ("Qual é a sua idade: ")
          leia (idade)
// uso do se
   se idade >= 18 entao
      escreval ("Você tem 18 anos ou mais")
      escreval ("Então você pode dirigir")
   senao
        escreval ("Você não tem idade para dirigir")
        escreval ("Negado!")
   fimse

fimalgoritmo

